#include "swc_io.h"
#include <QFile>
#include <QTextStream>
#include <iostream>

using namespace std;

bool export_list2file(QList<NeuronSWC>& lN, QString fileSaveName, QString fileOpenName)
{
    QFile file(fileSaveName);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
        return false;
    QTextStream myfile(&file);

    // Copy comment headers from original file if provided
    if (!fileOpenName.isEmpty())
    {
        QFile qf(fileOpenName);
        if (qf.open(QIODevice::ReadOnly | QIODevice::Text))
        {
            while (!qf.atEnd())
            {
                char _buf[1000], *buf;
                qf.readLine(_buf, sizeof(_buf));
                for (buf = _buf; (*buf && *buf == ' '); buf++); // skip leading spaces
                if (buf[0] == '\0') continue;
                if (buf[0] == '#')
                {
                    QString info = buf;
                    myfile << info.remove('\n') << Qt::endl;
                }
            }
            qf.close();
        }
    }
    else
    {
        myfile << "# generated by Algorithm CLI tool" << Qt::endl;
        myfile << "#n,type,x,y,z,radius,parent" << Qt::endl;
    }

    bool is_eswc = fileSaveName.endsWith(".eswc", Qt::CaseInsensitive);

    for (V3DLONG i = 0; i < lN.size(); i++)
    {
        myfile << lN.at(i).n << " " << lN.at(i).type << " "
               << lN.at(i).x << " " << lN.at(i).y << " "
               << lN.at(i).z << " " << lN.at(i).r << " "
               << lN.at(i).pn;

        if (is_eswc)
        {
            myfile << " " << lN.at(i).seg_id
                   << " " << lN.at(i).level
                   << " " << lN.at(i).creatmode
                   << " " << lN.at(i).timestamp
                   << " " << (long)lN.at(i).tfresindex;
            for (int f = 0; f < lN.at(i).fea_val.size(); f++)
                myfile << " " << lN.at(i).fea_val.at(f);
        }
        myfile << "\n";
    }

    file.close();
    cout << "swc file " << fileSaveName.toStdString() << " has been generated, size: " << lN.size() << endl;
    return true;
}
